
version: build{build}
image: Visual Studio 2019
services: mssql2017
clone_folder: C:\CKli-World\CK-AspNet-Projects\CK-AspNet-Auth
branches:
  only:
    - master
    - develop
environment:
  SqlServer/MasterConnectionString: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
install:
  - cmd: npm install -g npm@7.17.0
  - ps: Install-Product node 12
artifacts:
  - path: '**\*.log'
    name: Log file
  - path: '**\*.trx'
    name: Visual studio test results file
  - path: '**\Tests\**\TestResult*.xml'
    name: NUnit tests result files
  - path: '**Tests\**\Logs\**\*'
    name: Log files
