version: build{build}
image: Visual Studio 2022
install:
- ps: Install-Product node 18 x64
services: mssql2017
clone_folder: C:\CKli-World\CK-AspNet-Projects\CK-AspNet-Auth
environment:
  SqlServer/MasterConnectionString: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
test: false
on_finish:
- ps: "'Get-ChildItem -Recurse *.log -exclude LastRun.log | % { Push-AppveyorArtifact $_.FullName }'"
build_script:
- dotnet run --project CodeCakeBuilder -nointeraction
